name: tap_github_demo
version: '1.0'
profile: meltano
config-version: 2
source-paths:
- models
analysis-paths:
- analysis
test-paths:
- tests
data-paths:
- data
macro-paths:
- macros
snapshot-paths:
- snapshots
target-path: ../.meltano/transformers/dbt/target
log-path: logs
modules-path: dbt_modules
clean-targets:
- ../.meltano/transformers/dbt/target
- dbt_modules
- logs
models:
  tap_github_demo:
    materialized: table
vars:
  tap_github:   # I CANNOT GET THESE TO RENDER env_vars what am I doing wrong?!
    tap_github_raw_database: postgres
    tap_github_raw_schema: public
